Dev
kessio/Rent-a-house-backend pull request #42
Opened 2023-04-01 14:23 UTC by kessio

2023-04-01 19:38 UTC, mcrd25 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good documentation 👍 
- Your routes look good enough 👍 
- Your controllers looks good enough 👍 
- Your models look good 👍 

## Required Changes ♻️
_Check the comments under the review._
- You must add tests. You can add using rspec
- Your README needs some cleaning up to look more professional
- Reference your Front-End PR is PR description

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] When doing tests, consider both positive and negative scenarios. what do you expect to happen when inputs are all good and what do you expect to happen when inputs are bad?


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 19:38 UTC, mcrd25 commented on app/models/user.rb
> +end
[OPTIONAL]

is there any validations you can implement for fields in your user model?

2023-04-05 11:06 UTC, Meltrust requested changes
_note: The team claims they are repeating the module in their PR description.  Therefore, reviewing normally as a first review, as requested._

Hi team,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  API is working well✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-04-06 14:10 UTC, mcrd25 commented
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- implemented changes to bst of ability 👍 

## Optional suggestions
- Remove the empty line to prevent the linter failure before merging

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 14:39 UTC, ecekpo commented
Done. Thanks

2023-04-07 08:56 UTC, merged